<?php 
namespace ELT\DynamicLink\Lookup;

class DomainLinks
{
    public static $links = [
        'eamt' => 'http://www.easyamharictyping.com',
        'eat' => 'http://www.easyarabictyping.com',
        'ept' => 'http://www.easypersiantyping.com',
        'eut' => 'http://www.easyurdutyping.com',
        'ent' => 'http://www.easynepalityping.com',
        'eht' => 'http://www.easyhindityping.com',
        'ebt' => 'http://www.easybengalityping.com',
        'est' => 'http://www.easysinhalatyping.com',
        'etht' => 'http://www.easythaityping.com',
        'en-to-am-translation' => 'http://www.easyhindityping.com/english-to-amharic-translation',
        'am-to-en-translation' => 'http://www.easyhindityping.com/amharic-to-english-translation',
        'en-to-ar-translation' => 'http://www.easyhindityping.com/english-to-arabic-translation',
        'ar-to-en-translation' => 'http://www.easyhindityping.com/arabic-to-english-translation',
        'en-to-fa-translation' => 'http://www.easyhindityping.com/english-to-persian-translation',
        'fa-to-en-translation' => 'http://www.easyhindityping.com/persian-to-english-translation',
        'en-to-ur-translation' => 'http://www.easyhindityping.com/english-to-urdu-translation',
        'ur-to-en-translation' => 'http://www.easyhindityping.com/urdu-to-english-translation',
        'en-to-ne-translation' => 'http://www.easynepalityping.com/english-to-nepali-translation',
        'ne-to-en-translation' => 'http://www.easynepalityping.com/nepali-to-english-translation',
        'en-to-hi-translation' => 'http://www.easyhindityping.com/english-to-hindi-translation',
        'hi-to-en-translation' => 'http://www.easyhindityping.com/hindi-to-english-translation',
        'en-to-bn-translation' => 'http://www.easyhindityping.com/english-to-bengali-translation',
        'bn-to-en-translation' => 'http://www.easyhindityping.com/bengali-to-english-translation',
        'en-to-si-translation' => 'http://www.easyhindityping.com/english-to-sinhala-translation',
        'si-to-en-translation' => 'http://www.easyhindityping.com/sinhala-to-english-translation',
        'en-to-my-translation' => 'http://www.easyhindityping.com/english-to-burmese-translation',
        'my-to-en-translation' => 'http://www.easyhindityping.com/burmese-to-english-translation',
        'en-to-th-translation' => 'http://www.easyhindityping.com/english-to-thai-translation',
        'th-to-en-translation' => 'http://www.easyhindityping.com/thai-to-english-translation',
        'en-to-km-translation' => 'http://www.easyhindityping.com/english-to-khmer-translation',
        'km-to-en-translation' => 'http://www.easyhindityping.com/khmer-to-english-translation',
        'en-to-lo-translation' => 'http://www.easyhindityping.com/english-to-lao-translation',
        'lo-to-en-translation' => 'http://www.easyhindityping.com/lao-to-english-translation',
        'en-to-vi-translation' => 'http://www.easyhindityping.com/english-to-vietnamese-translation',
        'vi-to-en-translation' => 'http://www.easyhindityping.com/vietnamese-to-english-translation',
        'en-to-tl-translation' => 'http://www.easyhindityping.com/english-to-filipino-translation',
        'tl-to-en-translation' => 'http://www.easyhindityping.com/filipino-to-english-translation',
        'en-to-id-translation' => 'http://www.easyhindityping.com/english-to-indonesian-translation',
        'id-to-en-translation' => 'http://www.easyhindityping.com/indonesian-to-english-translation',
        'en-to-ms-translation' => 'http://www.easyhindityping.com/english-to-malay-translation',
        'ms-to-en-translation' => 'http://www.easyhindityping.com/malay-to-english-translation',
    ];
}
